In [140]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
df = pd.read_csv("../input/train.csv")
y = df.SalePrice.values
categorical = ['SalePrice', 'LotFrontage', 'Neighborhood', 'MasVnrArea', 'ExterQual',
       'BsmtQual', 'KitchenQual', 'FireplaceQu', 'GarageYrBlt', 'GarageFinish',
       'OverallQual', 'YearBuilt', 'TotalBsmtSF', '1stFlrSF', 'GrLivArea',
       'FullBath', 'TotRmsAbvGrd', 'GarageCars', 'GarageArea']
df = df.fillna("None") #make the ones with nan objects so that they can be re encoded with nan included
class PrepareData:
    def __init__(self, df, cat):
        self.df = df[cat+["Id"]]
        self.categories = cat
        print(self.df.select_dtypes("object").columns)
    def encode(self):
        catDf = self.df[list(self.df.select_dtypes("object").columns) + ["Id","SalePrice"]]
        for x in self.df.select_dtypes("object").columns:
            kf = self.df.groupby(x)["SalePrice"].mean().to_frame().sort_values("SalePrice")
            kf = kf.reset_index().reset_index().rename(columns={"index":x+"Encoded"}).drop(columns=["SalePrice"])
            catDf = catDf.merge(kf, on=x, how="left")
        self.catDf = catDf
        catDf = catDf[[x for x in catDf.columns if "Encode" in x or x in ["SalePrice","Id"]]]
        catDf.columns = [x.split("Encoded")[0] for x in catDf.columns]
        self.df = catDf.merge(self.df.select_dtypes(include=['float64',"int64"]), on=["Id","SalePrice"])
obj = PrepareData(df, categorical)
obj.encode()
df = obj.df

Index(['LotFrontage', 'Neighborhood', 'MasVnrArea', 'ExterQual', 'BsmtQual',
       'KitchenQual', 'FireplaceQu', 'GarageYrBlt', 'GarageFinish'],
      dtype='object')

In [139]:
df[df.select_dtypes(exclude=["object"]).isnull().any(axis=1)]

,Id,SalePrice,Neighborhood,ExterQual,BsmtQual,KitchenQual,FireplaceQu,GarageFinish,LotFrontage,MasVnrArea,GarageYrBlt,OverallQual,YearBuilt,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,GarageCars,GarageArea
0,1,208500,16,2,2.0,2,NaN,1.0,65.0,196.0,2003.0,7,2003,856,856,1710,2,8,2,548
5,6,143000,11,1,2.0,1,NaN,0.0,85.0,0.0,1993.0,5,1993,796,796,1362,1,5,2,480
7,8,200000,13,1,2.0,1,2.0,1.0,NaN,240.0,1973.0,7,1973,1107,1107,2090,2,7,2,484
10,11,129500,6,1,1.0,1,NaN,0.0,70.0,0.0,1965.0,5,1965,1040,1040,1040,1,5,1,384
12,13,144000,6,1,1.0,1,NaN,0.0,NaN,0.0,1962.0,5,1962,912,912,912,1,4,1,352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1452,1453,145000,4,1,2.0,1,NaN,2.0,35.0,80.0,2005.0,5,2005,547,1072,1072,1,5,2,525
1453,1454,84500,11,1,2.0,1,NaN,NaN,90.0,0.0,NaN,5,2006,1140,1140,1140,1,6,0,0
1454,1455,185000,19,2,2.0,2,NaN,1.0,62.0,0.0,2004.0,7,2004,1221,1221,1221,2,6,2,400
1458,1459,142125,10,1,1.0,2,NaN,0.0,68.0,0.0,1950.0,5,1950,1078,1078,1078,1,5,1,240
1459,1460,147500,4,2,1.0,1,NaN,2.0,75.0,0.0,1965.0,5,1965,1256,1256,1256,1,6,1,276

In [123]:
from ipywidgets import IntProgress

In [141]:
X = df.iloc[:,2:]

In [142]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [143]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

model = lm.fit(x_train, y_train)

y_predict= lm.predict(x_test)

In [145]:
from sklearn.metrics import r2_score
print("Test score:")
r2_score(y_test, y_predict)

Test score:

0.8431824004863517

In [135]:
# Necessary imports 
import numpy as np 
import pandas as pd 
import xgboost as xg 
from sklearn.model_selection import train_test_split 
from sklearn.metrics import mean_squared_error as MSE 
# Instantiation 
xgb_r = xg.XGBRegressor(objective ='reg:linear', 
                  n_estimators = 10, seed = 123) 
  
# Fitting the model 
xgb_r.fit(x_train, y_train) 
  
# Predict the model 
predictions = xgb_r.predict(x_test) 

# RMSE Computation 
rmse = np.sqrt(MSE(y_test, predictions)) 
print("RMSE : % f" %(rmse))

RMSE :  32578.117220

In [137]:
from tpot import TPOTClassifier
from tpot import TPOTRegressor

tpot = TPOTRegressor(generations=5,verbosity=2)
tpot.fit(x_train, y_train)

Imputing missing values in feature set

ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

In [125]:
jupyter nbextension enable --py widgetsnbextension

SyntaxError: invalid syntax (<ipython-input-125-98201c4d83e5>, line 1)